version: '3.8'

services:
  claude-proxy:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOWED_API_KEYS=${ALLOWED_API_KEYS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEEPSEEK_THINKING=${DEEPSEEK_THINKING:-false}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped